# Generated by Django 4.2.9 on 2024-01-19 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPartModel',
            fields=[
                ('sub_category', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katalog', models.CharField(choices=[("Muddatli To'lov", "Muddatli To'lov"), ("Yangi yil sovg'alari", "Yangi yil sovg'alari"), ('Elektronika', 'Elektronika'), ('Maishiy Texnika', 'Maishiy Texnika'), ('Kiyim', 'Kiyim'), ('Poyabzallar', 'Poyabzallar'), ('Aksessuarlar', 'Aksessuarlar'), ("Go'zallik va Parvarish", "Go'zallik va Parvarish"), ('Salomatlik', 'Salomatlik'), ("Uy-ro'zg'or buyumlari", "Uy-ro'zg'or buyumlari"), ("Qurilish va Ta'mirlash", "Qurilish va Ta'mirlash"), ('Avtotovarlar', 'Avtotovarlar'), ('Bolalar tovarlari', 'Bolalar tovarlari'), ('Xobbi va ijod', 'Xobbi va ijod'), ('Sport va Xordiq', 'Sport va Xordiq'), ('Oziq-Ovqat mahsulotlari', 'Oziq-Ovqat mahsulotlari'), ('Maishiy kimyoviy moddalar', 'Maishiy kimyoviy moddalar'), ('Kanselariya tovarlari', 'Kanselariya tovarlari'), ('Hayvonlar uchun tovarlar', 'Hayvonlar uchun tovarlar'), ('Kitoblar', 'Kitoblar'), ("Dacha, Bog' va tomorqa", "Dacha, Bog' va tomorqa")], max_length=255)),
                ('kategoriya', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SalerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('PS_serial_num', models.IntegerField(unique=True)),
                ('PS_seria', models.CharField(max_length=2)),
                ('phone', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.IntegerField()),
                ('product_image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('last_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalerApp.categorypartmodel')),
            ],
        ),
        migrations.AddField(
            model_name='categorypartmodel',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalerApp.productmodel'),
        ),
    ]
