# Generated by Django 4.2.9 on 2024-01-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, unique=True)),
                ('tel_raqam', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=32)),
                ('ps_seriya', models.CharField(max_length=2)),
                ('ps_seriya_raqam', models.IntegerField(unique=True)),
            ],
        ),
    ]
